### ISSUE TITLE
DgmlImage issue?

### ISSUE THREAD

**Issue by TheXenocide** [lovettchris/lovettchris.github.io#2]
I don't know if you'll see this and it doesn't seem like exactly the right place, but I was hoping to get in touch because I am a big fan of DgmlImage, but have ran into a few things in recent history that make me wish we could get an updated version. 

To start, it would be nice if it used latest assemblies, since it now renders differently than Visual Studio does sometimes (icons have changed, some types of links in VS also no longer seem to honor certain stroke color styling?)

That's not as important as the fact that I sometimes get a Abort/Retry/Ignore message box from an assertion failure which causes non-interactive automations like CI builds to get stuck waiting for the user to select a response. Would be nice to see the error in the output and default to not showing the dialog, though if you still find some use in it maybe it could be controlled by a command line switch?

It also sometimes crashes when encountering long file names; I can work around this one in most case, but we have the necessary registry setting enabled to support long paths, but applications have to opt-in to the behavior with an application manifest.

```
Application: DgmlImage.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.PathTooLongException
   at System.IO.Path.LegacyNormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.InternalGetDirectoryName(System.String)
   at DgmlImage.Program.FindMatchingFiles(System.Collections.Generic.List`1<System.String>)
   at DgmlImage.Program.ParseCommandLine(System.String[])
   at DgmlImage.Program.Main(System.String[])
```

I don't have a million dollars or anything, but I appreciate this utility enough that I would even be willing to sponsor the work, if a spare $50 would make it more likely to get done?

**Comment by lovettchris** [comment]
Thanks for the detailed bug report, yeah I'll try and catch asserts and log them and I haven't tested it with long file names, I'll try and get a fix released soon...  It would be helpful if you have a dgml handy that reproduces the popup asserts...

**Comment by TheXenocide** [comment]
Oh wow, that was really a prayer on the wind github issue, thanks for replying so promptly. I was actually headed back because I managed to catch an assertion dialog exception in the wild today today:
![image](https://github.com/user-attachments/assets/2d9cb4a0-4e6b-4b1e-bc40-b0cd34d1b0e5)

It happened locally and I was able to attach a debugger, so this is the full stack trace I saw:

```
>	System.dll!System.Diagnostics.AssertWrapper.ShowMessageBoxAssert(string stackTrace, string message, string detailMessage) Line 162	C#
 	System.dll!System.Diagnostics.DefaultTraceListener.Fail(string message, string detailMessage) Line 106	C#
 	System.dll!System.Diagnostics.TraceInternal.Fail(string message) Line 225	C#
 	Layout.dll!Microsoft.VisualStudio.Diagrams.Layout.LayoutWorker.NotifyLayoutError(Microsoft.VisualStudio.Diagrams.Layout.LayoutErrorEventArgs args)	Unknown
 	Layout.dll!Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.LayoutErrorUpdate.Apply(Microsoft.VisualStudio.Diagrams.Layout.LayoutWorker worker)	Unknown
 	Layout.dll!Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.Apply.AnonymousMethod__21_0(Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.IForegroundUpdate u)	Unknown
 	mscorlib.dll!System.Collections.Generic.List<Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.IForegroundUpdate>.ForEach(System.Action<Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.IForegroundUpdate> action) Line 557	C#
 	Layout.dll!Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.Apply()	Unknown
 	Layout.dll!Microsoft.VisualStudio.Diagrams.Layout.ForegroundUpdateQueue.DispatchApply.AnonymousMethod__22_0()	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 980	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 927	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 916	C#
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)	Unknown
 	DgmlImage.exe!DgmlImage.Program.ProcessFile(string path)	Unknown
 	DgmlImage.exe!DgmlImage.Program.ProcessFiles()	Unknown
 	DgmlImage.exe!DgmlImage.Program.Main(string[] args)	Unknown
```

**Comment by TheXenocide** [comment]
I also just found [this note about AssertWrapper](https://www.hanselman.com/blog/preventing-dialogs-on-the-serverside-in-aspnet-or-tracefail-considered-harmful), so maybe this will already be a non-issue in CI environments? Otherwise, it looks like just an app.config setting?

**Comment by TheXenocide** [comment]
Sorry, just realized you asked about a specific DGML, next time I'll try to get a view on which one it's stuck on (it only happened once or twice during a multi-threaded batch of ~800 dgmls). It occurs to me though that the diagrams in question are somewhat sensitive, would there be a better way to share one when I find it? I worry that sanitizing it could be a fair amount of work and not produce the same results.

**Comment by lovettchris** [comment]
You can email them to me if you are ok with sharing them with me.  But the contents of the popup would also be helpful so I can try and reproduce it.  My email is the first letter of my first name and my last name at the company that I'm affiliated with in my github.  Dang, that is still too easy for chatgpt to figure out :-)

**Comment by TheXenocide** [comment]
Well I managed to capture a DGML that resulted in the popup, but unfortunately rerunning it does not reproduce the issue. I'm sending it along anyway, in case it helps, but I guess it being a temperamental type of issue could explain why I only noticed it happen a few times despite having run the same (or roughly similar) generation code many times.

**Comment by TheXenocide** [comment]
I could possibly capture a memory dump next time I see it, though I am actually on vacation next week.

**Comment by clovett** [comment]
I published a new version over here
https://github.com/clovett/DgmlPowerTools/releases/tag/1.6.0.11

So let's also move any future discussions about it to the DgmlPowerTools issues list, thanks.

**Comment by TheXenocide** [comment]
Awesome, will give it a try soon. Thanks so much!
